library(shiny)
library(shinyjs)
library(plyr)
library(dplyr)
library(shinythemes)
library(shinydashboard)
library(stringr)
library(DT)
library(jsonlite)
library(reticulate)
library(ggplot2)
library(purrr)
library(plotly)
library(waiter)

#########global
use_condaenv('synapse', required = TRUE)
reticulate::import("sys")

source_python("syn_login_func.py")
